
-- What is the total number of rows in each of the three tables in the database?
Select 
	count(*) as 'Row_count_customer'
From dbo.Customer

Select 
	count(*) as 'Row_count_product_category'
From dbo.product_category

Select 
	count(*) as 'Row_count_transactions'
From dbo.Transactions

-- What is the total number of transactions that have a return?

Select 
	count(*) as 'Return_Transactions' 
From dbo.Transactions
Where 
	Qty < 0

-- Date correct format
SELECT
	CONVERT(VARCHAR, CAST(DOB AS DATE), 103) AS FormattedDOB
FROM dbo.Customer

SELECT 
	CONVERT(VARCHAR, tran_date, 103) AS FormattedTranDate
FROM Transactions

-- What is the time range of the transaction data available for analysis? Show the output in number of days, months and years simultaneously in different columns.
SELECT
    DATEDIFF(day, MIN(tran_date), MAX(tran_date)) AS'number_of_days',
    DATEDIFF(month, MIN(tran_date), MAX(tran_date)) AS 'number_of_months',
    DATEDIFF(year, MIN(tran_date), MAX(tran_date)) AS 'number_of_years'
from dbo.Transactions

-- Which product category does the sub-category "DIY" belong to
Select *
from 
	dbo.product_category
where 
	prod_subcat = 'DIY'

-- Data analysis
-- Which channel is most frequently used for transactions?
Select
Store_type,
	count(cust_id) as 'Transaction_count'
from dbo.Transactions
Group by 
	Store_type
Order by 
	Transaction_count Desc

-- What is the count of male and female customers in the database?
Select
	Gender,
	count(customer_id) as 'customer_count_by_gender'
from 
	dbo.Customer
Group by 
	Gender

-- From which city do we have the maximum number of customers and how many?
Select
	city_code,
	count(customer_id) as 'number_of_customers_by_city_code'
from 
	dbo.Customer
Group by 
	city_code
Order by 
	number_of_customers_by_city_code desc

-- How many sub-categories are there under the books category?
Select 
	prod_cat,
	prod_subcat
From 
	dbo.product_category
Where 
	prod_cat = 'Books'
Order by 
	prod_subcat asc

-- What is the maximum quantity of products ever ordered?
Select 
	product_category.prod_cat,
	sum(Qty) as 'total_quantity_by_prod_cat'
from dbo.Transactions
join 
	dbo.product_category on dbo.Transactions.prod_cat_code = dbo.product_category.prod_cat_code
Group by
	product_category.prod_cat
Order by
	total_quantity_by_prod_cat desc

-- What is the net total revenue generated on categories Electronics and Books
Select 
	product_category.prod_cat,
	sum(total_amt) as 'total_revenue_by_prod_cat'
from 
	dbo.Transactions
join 
	dbo.product_category on dbo.Transactions.prod_cat_code = dbo.product_category.prod_cat_code
Group by
	product_category.prod_cat
Order by
	total_revenue_by_prod_cat desc

-- How many customers have > 10 transactions with us excluding returns
Select
cust_id,
count(transaction_id) as 'count_of_transactions'
from dbo.Transactions
where Qty > 0
Group by cust_id
Having count(transaction_id) > 10
Order by count_of_transactions Desc

-- What is the combined revenue earned from the electronics and clothing categories from flagship stores?
Select
    Store_type,
    dbo.product_category.prod_cat,
    SUM(total_amt) as 'Revenue'
From 
	dbo.Transactions
Join 
	dbo.product_category on dbo.Transactions.prod_cat_code = dbo.product_category.prod_cat_code
Where 
	Store_type = 'Flagship store'
Group by 
	Store_type, dbo.product_category.prod_cat
Having	
	dbo.product_category.prod_cat IN ('Electronics', 'Clothing')

-- What is the total revenue generated from male customers in electronics category? output should display total revenue by product sub-cat.
Select
	p.prod_subcat,
sum (total_amt) as Total_revenue
From 
	Transactions t
Join 
	Customer c on t.cust_id = c.customer_Id
join 
	product_category p on t.prod_cat_code = p.prod_cat_code and t.prod_subcat_code = p.prod_sub_cat_code
where
	c.Gender = 'M'
		and p.prod_cat = 'Electronics'
Group by 
	p.prod_subcat
Order by Total_revenue Desc

-- What is the percentage of sales and returns by product_sub_category. display only top 5 sub-categories in terms of sales?
with subcatsalesretuns as
(Select
prod_subcat,
sum(case when t.total_amt > 0 then t.total_amt else 0 end) as total_sales,
sum(case when t.total_amt < 0 then t.total_amt else 0 end) as total_returns
from dbo.Transactions t
join dbo.product_category p on t.prod_cat_code = p.prod_cat_code and t.prod_subcat_code = p.prod_sub_cat_code
group by prod_subcat
)
Select Distinct
prod_subcat,
total_sales,
total_returns,
(total_sales/(total_sales+total_returns) *100) as 'percentage_sales',
(total_returns/(total_sales+total_returns)*100) as 'percentage_returns'
from subcatsalesretuns
where total_sales >= 2480000
order by
total_sales desc


-- For all customers aged between 25 years to 35 years find what is the net total revenue generated by these customers 
-- in last 30 days of transactions from max transaction available data available in the data?
WITH customerage25to35 AS
(
    SELECT 
        customer_Id,
        DOB,
        Gender,
        city_code,
        DATEDIFF(YEAR, DOB, GETDATE()) AS Age
    FROM 
        dbo.Customer
    WHERE 
        DATEDIFF(YEAR, DOB, GETDATE()) BETWEEN 25 AND 35
)
SELECT
dbo.Transactions.tran_date,
    SUM(dbo.Transactions.total_amt) AS revenue
FROM 
    dbo.Transactions
JOIN 
    customerage25to35 ON dbo.Transactions.cust_id = customerage25to35.customer_Id
where CONVERT(DATE, dbo.Transactions.tran_date, 105) > '2014-01-25'
group by dbo.Transactions.tran_date
order by tran_date desc


-- Which product category has seen the max value of returns in the last 3 months of transactions?

Select
	dbo.product_category.prod_cat,
	sum(Qty) as 'total_qty',
	CAST(ROUND(SUM(total_amt), 0) AS INT) AS total_returns
from 
	dbo.Transactions
join 
	dbo.product_category on dbo.Transactions.prod_cat_code = dbo.product_category.prod_cat_code
where 
	Qty < 0 
AND 
	tran_date >= DATEADD(MONTH, -3, (SELECT MAX(tran_date) FROM dbo.Transactions))
Group by 
	dbo.product_category.prod_cat
Order by 
	total_returns asc


-- Which store sells the maximum products by value of sales amount and by quantity sold?

Select
	Store_type,
	sum(qty) as 'Total_quantity_sold',
	sum(total_amt) as 'Total_sales'
From 
	dbo.Transactions
join dbo.product_category on dbo.Transactions.prod_cat_code = dbo.product_category.prod_cat_code
Group by 
	Store_type
Order by 
	Total_sales desc

-- What are the categories for which average revenue is above overall average?
WITH OverallAvg AS (
SELECT AVG(total_amt) AS Overall_Avg
FROM dbo.Transactions
)
SELECT
pc.prod_cat,
SUM(t.qty) AS Total_quantity_sold,
AVG(t.total_amt) AS Avg_sales,
oa.Overall_Avg
FROM 
    dbo.Transactions t
JOIN 
    dbo.product_category pc ON t.prod_cat_code = pc.prod_cat_code
CROSS JOIN
    OverallAvg oa
GROUP BY 
    pc.prod_cat, oa.Overall_Avg
HAVING
    AVG(t.total_amt) > oa.Overall_Avg
ORDER BY 
    Avg_sales DESC


-- Find the average and total revenue by each sub-category for the categories which are among the top 5 categories in terms of qty sold?

WITH TopCategories AS (
    SELECT 
        dbo.product_category.prod_cat,
        SUM(qty) AS Total_quantity_sold,
        ROW_NUMBER() OVER (ORDER BY SUM(qty) DESC) AS rn
    FROM 
        dbo.Transactions
	join dbo.product_category on dbo.Transactions.prod_cat_code = dbo.product_category.prod_cat_code
    GROUP BY 
        prod_cat
)
SELECT
    pc.prod_cat,
    pc.prod_subcat,
    SUM(t.qty) AS Total_quantity_sold,
    SUM(t.total_amt) AS Total_sales,
    AVG(t.total_amt) AS Avg_sales
FROM 
    dbo.Transactions t
JOIN 
    dbo.product_category pc ON t.prod_cat_code = pc.prod_cat_code AND t.prod_subcat_code = pc.prod_sub_cat_code
WHERE 
    pc.prod_cat IN (SELECT prod_cat FROM TopCategories WHERE rn <= 5)
GROUP BY 
    pc.prod_cat,
    pc.prod_subcat
ORDER BY
	prod_cat ASC,
    Total_sales DESC
